### ISSUE TITLE
Error: Duplicate plugin/preset detected

### ISSUE THREAD

**Issue by m00k** [callstack/linaria#781] opened 2021-06-18 03:22 UTC
## Environment

- Linaria version:
```json
    "@linaria/babel-preset": "^3.0.0-beta.5",
    "@linaria/core": "^3.0.0-beta.4",
    "@linaria/react": "^3.0.0-beta.4",
    "@linaria/shaker": "^3.0.0-beta.5",
    "@linaria/webpack-loader": "^3.0.0-beta.6",
```
- Bundler (+ version):
```
npm ls webpack
├─┬ @linaria/webpack-loader@3.0.0-beta.6
│ └─┬ @linaria/webpack5-loader@3.0.0-beta.6
│   └─┬ webpack@5.39.1
│     └─┬ terser-webpack-plugin@5.1.3
│       └── webpack@5.39.1 deduped
└─┬ preact-cli@3.2.2
  ├─┬ @prefresh/webpack@3.3.0
  │ └── webpack@4.46.0 deduped
  ├─┬ babel-esm-plugin@0.9.0
  │ └── webpack@4.46.0 deduped
  ├─┬ babel-loader@8.2.2
  │ └── webpack@4.46.0 deduped
 ...
```
- Node.js version: 16.3.0
- OS: Linux

## Description

Building a preact application with a [styled custom component](https://github.com/callstack/linaria/blob/master/docs/BASICS.md#styling-custom-components) fails with `Error: Duplicate plugin/preset detected`.
Might be related to #734 

## Reproducible Demo

https://github.com/m00k/linaria-duplicate-plugins
```npm run build```
```
...
Error: Duplicate plugin/preset detected.
...
Duplicates detected are:
[
  {
    "alias": "./node_modules/babel-plugin-transform-react-remove-prop-types/lib/index.js",
    "dirname": ".",
    "ownPass": false,
    "file": {
      "request": "./node_modules/babel-plugin-transform-react-remove-prop-types/lib/index.js",
      "resolved": "./node_modules/babel-plugin-transform-react-remove-prop-types/lib/index.js"
    }
  },
  {
    "alias": "./node_modules/babel-plugin-transform-react-remove-prop-types/lib/index.js",
    "dirname": ".",
    "ownPass": false,
    "file": {
      "request": "./node_modules/babel-plugin-transform-react-remove-prop-types/lib/index.js",
      "resolved": "./node_modules/babel-plugin-transform-react-remove-prop-types/lib/index.js"
    }
  }
]
```

**Comment by Anber** [comment] 2021-06-22 07:29
Hi @m00k 

It's a duplicate of https://github.com/callstack/linaria/issues/734. I know about this problem and I'm trying to solve it…

**Closed by Anber** 2021-06-22 07:29 UTC
Labels: bug report 🦗, bundler: webpack 📦, cat: modules aliasing 🔗, needs: complete repro 🖥️
