### ISSUE TITLE
Tags parsing is still too aggressive

### ISSUE THREAD

**Issue by therealgilles** [callstack/linaria#1224] opened 2023-03-09 19:49 UTC
See: https://github.com/callstack/linaria/issues/1214#issue-1592165301

This case is still not fixed:
```TSX
import { styled } from '@linaria/react';

export type StyledReturn = ReturnType<typeof styled>;
```
results in:
```
SyntaxError: /home/projects/node-hyqpx9/code/exampleA.ts: /home/projects/node-hyqpx9/code/exampleA.ts: Invalid usage of `styled` tag
  1 | import { styled } from '@linaria/react';
  2 |
> 3 | export type StyledReturn = ReturnType<typeof styled>;
    |     
```

## Reproducible Demo
Same as previous issue: [stackblitz.com/edit/node-hyqpx9](https://stackblitz.com/edit/node-hyqpx9)

**Comment by therealgilles** [comment] 2023-03-09 19:52
@andparsons Any chance you could take a look at this soon-ish? is there a possible workaround to disable the `validateParams()`?

**Comment by Anber** [comment] 2023-04-24 14:34
Hi @therealgilles!

Sorry for the delay :( The problem is fixed in https://github.com/callstack/linaria/pull/1239. The fix will be released with the next version in a few hours.

**Closed** 2023-04-24 14:37 UTC
Labels: needs: complete repro 🖥️, bug report 🦗
