### ISSUE TITLE
Add class composition feature

### ISSUE THREAD

**Issue by silvenon** [callstack/linaria#243] opened 2018-10-10 10:16 UTC
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the desired behavior?**

```jsx
import { css } from 'linaria'
import { styled } from 'linaria/react'

const card = css`
  background: #fff;
  box-shadow:
    0 1px 3px rgba(0, 0, 0, 0.12),
    0 1px 2px rgba(0, 0, 0, 0.24);
`

const Container = styled.div`
  font-family: sans-serif;
  ${card};
`
```

Is it possible/hard to make interpolating `card` result in Container receiving its styles with class composition? ([Inspired by emotion](https://emotion.sh/docs/composition).)

**Please provide your exact Babel configuration and mention your Linaria, Node, Yarn/npm version and operating system.**

```js
// babel.config.js
module.exports = {
  presets: [
    '@babel/preset-env',
    '@babel/preset-react',
    'linaria/babel',
  ]
}
```

```
Linaria: 1.0.0-alpha.8
Node: 10.11.0
Yarn: 1.10.1
```

**Comment by satya164** [comment] 2018-10-10 15:32
I just created an RFC - #244 

Will be great if you can check it and give some feedback.

**Comment by jayu** [comment] 2020-04-01 19:02
It's kind of duplicate of mentioned issue, I'm closing

**Closed by jayu** 2020-04-01 19:02 UTC
Labels: feature: proposal 💬
