### ISSUE TITLE
Typescript Definitions not loading in 1.4.0-beta.0

### ISSUE THREAD

**Issue by mattoni** [callstack/linaria#520] opened 2020-01-03 18:20 UTC
## Environment

Typescript 3.7.3

## Description

Typescript definitions for `import {styled} from "linaria/react"` are no longer working. The definitions are in the lib, but there are no longer definitions in the root folder, so TS doesn't know where to find them. 

## Reproducible Demo

Try importing styled from linaria/react in any typescript project and it will fail.

**Comment by Anber** [comment] 2020-01-03 18:34
Unfortunately, if I properly understood, it’s impossible to fix that issue without splitting Linaria to different npm-packages. So, it’s kind of a duplicate of https://github.com/callstack/linaria/issues/413

**Comment by mattoni** [comment] 2020-01-03 18:48
I'm not sure why it would be any different than the current live version in the meantime, if you could possibly keep the definitions in the root until you split it, that would allow it to keep working normally in typescript.

**Comment by aweber1** [comment] 2020-01-07 23:13
As a workaround in the meantime, you can change `import {styled} from "linaria/react"` to `import { styled } from 'linaria/lib/react';` to load the typings.

**Comment by Anber** [comment] 2020-01-12 13:32
@mattoni yep, you are right. Looks like we lost a couple of d.ts files. Thank you!

**Comment by Anber** [comment] 2020-03-27 08:49
It was fixed in one of the latest betas.

**Closed by Anber** 2020-03-27 08:49 UTC
