### ISSUE TITLE
Linaria 6: broken :global selector (regression)

### ISSUE THREAD

**Issue by PierreGUI** [callstack/linaria#1388] opened 2023-12-19 12:57 UTC
## Environment
Linaria version: 6
Bundler: Webpack 5

## Description
Original question: "Linaria 6: space between classname and pseudo element selector (regression)", rephrased based on answers, see below.  
This code generates a class name with **an unwanted space:** `.dhnsy8v ::after {`  
```js
const Decorated = styled.h1`
  ::after {
     ...
  }
`;
```

The expected behaviour is **no space between classname and ::after**

## Reproducible Demo
https://stackblitz.com/edit/linaria-bug-y4gxid?file=src%2FTitle.tsx

- It works with Linaria 5
- It works when written `&::after { ... }`

**Comment by PierreGUI** [comment] 2023-12-19 14:38
PS: same problem with `:hover` -> `.dhnsy8v :hover {` :x:

**Comment by PierreGUI** [comment] 2023-12-20 10:09
BTW this is the reason why Linaria's own website looks a bit off https://linaria.dev 

![image](https://github.com/callstack/linaria/assets/1013904/b2cb4801-8aae-44e6-bb8a-3969a7e7414a)

**Comment by agriffis** [comment] 2023-12-25 11:59
This isn't really a regression, rather it's a breaking change in v6. It's because of stylis v4, see https://github.com/callstack/linaria/pull/1373

The new behavior matches SCSS and other preprocessors. Linaria was previously an outlier, and anyone migrating had to change their nested selectors.

**Comment by alekseykulikov** [comment] 2023-12-26 11:18
I confirm that the documented `:global()` selector doesn't work in v6 (https://linaria.dev is an excellent proof). Do you have any suggestions on how to define global styles with v6?

**Comment by agriffis** [comment] 2023-12-26 14:00
> I confirm that the documented `:global()` selector doesn't work in v6 (https://linaria.dev is an excellent proof). Do you have any suggestions on how to define global styles with v6?

I'm finding the same thing. It seems Linaria or wyw-in-js needs an adjustment to enable global styles with Stylis v4, but I haven't yet traced the code to understand how it is intended to work.

**Comment by agriffis** [comment] 2023-12-27 17:14
So it appears that we need the `namespace` middleware to support `:global()` rules.

When I add it to wyw like this:

```
diff --git a/packages/transform/src/transform/generators/extract.ts b/packages/transform/src/transform/generators/extract.ts
index 215d27b..66aec9f 100644
--- a/packages/transform/src/transform/generators/extract.ts
+++ b/packages/transform/src/transform/generators/extract.ts
@@ -2,7 +2,14 @@ import path from 'path';
 
 import type { Mapping } from 'source-map';
 import { SourceMapGenerator } from 'source-map';
-import { compile, serialize, stringify, middleware, prefixer } from 'stylis';
+import {
+  compile,
+  serialize,
+  stringify,
+  middleware,
+  namespace,
+  prefixer,
+} from 'stylis';
 
 import type { Replacements, Rules } from '@wyw-in-js/shared';
 
@@ -50,6 +57,7 @@ function createStylisPreprocessor(options: Options) {
             );
           }
         },
+        namespace,
         prefixer,
         stringify,
       ])
```

then `:global(html) {...}` works but `:global() {html {...}}` doesn't. It's progress but still broken.

Unfortunately the [code for the namespace middleware](https://github.com/thysultan/stylis/blob/master/src/Middleware.js#L75-L112) is garbage. It might be faster to come up with a new replacement middleware than to debug it.

**Comment by jancajthaml** [comment] 2024-01-12 18:35
Any update or plan to tackle this issue?

**Comment by layershifter** [comment] 2024-01-19 10:23
I kinda agree with `:hover` behavior as it's also how `styled-components` work:
- https://stackblitz.com/edit/stackblitz-starters-wrkniy
- https://styled-components.com/docs/basics#extending-styles

However, the issue with `:global()` is a problem. I will work on the plugin to stylis as `namespace` plugin from it does not do what is expected and had to write a plugin for Griffel before (https://github.com/microsoft/griffel/blob/45e2a6b41596862bc2c54efbcbe746dc041e025e/packages/core/src/runtime/stylis/globalPlugin.ts#L1).

**Comment by layershifter** [comment] 2024-01-22 18:06
The fix was done in https://github.com/Anber/wyw-in-js/pull/37 and released in `@wyw-in-js/*@0.2.3`.

**Closed** 2024-01-22 18:11 UTC
Labels: needs: complete repro 🖥️, bundler: webpack 📦, bug report 🦗

**Comment by Dozalex** [comment] 2024-01-23 07:29
@layershifter Thanks for your fix! But I see another problem with :global

If i do
```ts
const globals = css`
  :global() {
    body {
      .someClassName {
        color: red;
      }
    }
  }
`
```
then I get the error `Failed to match :global() selector in ".someClassName". Please report a bug if it happens`.

If i do
```ts
const globals = css`
  :global() {
    body.someClassName {
      color: red;
    }
  }
`
```
then no error.

It's not a big problem, but before version 6 it worked this way and that way.

**Comment by nihgwu** [comment] 2024-01-29 23:27
Ran into the same issue as @Dozalex and it's a big issue for me as I'm using nested style with `&`, don't know how to workaround it

**Comment by layershifter** [comment] 2024-01-30 16:40
@Dozalex seems that my change should be improved 🤔 I will try to fix it next week until somebody will do it earlier 🐱

**Comment by nihgwu** [comment] 2024-01-30 19:54
can we just have a `globalCss` instead 🤔
