### ISSUE TITLE
Gatsby build warnings with mini-css-extract-plugin

### ISSUE THREAD

**Issue by kuworking** [callstack/linaria#671] opened 2020-09-05 10:55 UTC
I am facing a few warnings when building a `Gatsby` site with `linaria`

```
warn chunk styles [mini-css-extract-plugin]
Conflicting order. Following module has been added:
* css ./node_modules/css-loader??ref--12-oneOf-1-1!./node_modules/postcss-loader/src??postcss-2!./.linaria-cache/src/components/theme/colors.linaria.css
despite it was not able to fulfill desired ordering with these modules:
 * css ./node_modules/css-loader??ref--12-oneOf-1-1!./node_modules/postcss-loader/src??postcss-2!./.linaria-cache/src/components/shared/emoji.linaria.css
   - couldn't fulfill desired order of chunk group(s) component---content-pages-lista-correo-js

etc
```

This error happens to me now that I use linaria, but it is not linaria specific 

From this question https://stackoverflow.com/questions/51971857/mini-css-extract-plugin-warning-in-chunk-chunkname-mini-css-extract-plugin-con/56256336 there is

> Q: What is the cause?
> 
> A: The plugin (mini-css-extract-plugin) tries to generate a CSS file but your codebase has multiple possible orderings for your modules. From the warning you showed, it seems you have used Icon before Counter in one location and Counter before Icon in another location. The plugin needs to generate a single CSS file from these and can't decide which module's CSS should be placed first. CSS cares for rule order so this can lead to issue when CSS changes without reason. So not defining a clear order can lead to fragile builds, that's why it displays a warning here.
> 
> Q: How to fix?
> 
> A: Sort your imports to create a consistent order. If you don't wanna bother yourself with that, you can ignore the warning with stats.warningFilter (as shown in the answer given by Czilla) when the order of these styles doesn't matter.

This solution has solved the warnings for me, so perhaps it would be useful if these instructions are included in the docs together with some guidelines about how to structure the files when using linaria (if this has sense)

**Comment by jayu** [comment] 2020-09-26 17:27
The issue is not related to linaria hence I'm closing

**Closed by jayu** 2020-09-26 17:27 UTC
Labels: enhancement: proposal 💬, needs: triage 🏷
