### ISSUE TITLE
Atomic ClassName Optimization

### ISSUE THREAD

**Issue by brandonkal** [callstack/linaria#426] opened 2019-05-29 11:05 UTC
I would like to propose an improvement in ClassName generation to produce smaller stylesheets. Have a look at CSSBlocks for an example of generating atomic classnames for shared styles. https://css-blocks.com/

Linaria is in a position to do the same. The css function would return classes with a dot so that they can be replaced in build time and continue to function in nested styles and used for querySelector(). For example: `title__a.shared__b`

The cx function would replace the dot with a space character when that now split class name is applied to an element.

Linaria and the promise of near zero runtime really excites me. Because it controls classnames applied in the template and the generated CSS, this improvement is possible.

**Comment by satya164** [comment] 2019-05-29 11:08
kind of similar to #218

**Comment by brandonkal** [comment] 2019-05-29 11:19
Yes, combined with shorter classnames, this would help save a lot of bytes! I'd argue this would be a larger performance win because the classnames length generated by Linaria is already pretty short but duplicated style declarations for different elements is common.

**Comment by jayu** [comment] 2020-04-01 19:31
This is a duplicate of the mentioned issue

**Closed by jayu** 2020-04-01 19:31 UTC
Labels: feature: proposal 💬
