### ISSUE TITLE
JSX element type 'Wrapper' does not have any construct or call signatures.

### ISSUE THREAD

**Issue by fabulator** [callstack/linaria#870] opened 2021-11-20 14:55 UTC
## Environment
- "typescript": "^4.5.2"
- "@linaria/babel-preset": "^3.0.0-beta.14",
- "@linaria/core": "^3.0.0-beta.13",
- "@linaria/react": "^3.0.0-beta.14",
- "@linaria/shaker": "^3.0.0-beta.14",
- "react": "^17.0.2",
- "react-dom": "^17.0.2",
- node -v v14.18.1

## Description

Hi, I have a problem with a typecheck of components. When I create styled component from a html element and use it I get ts error: "TS2604: JSX element type 'Wrapper' does not have any construct or call signatures."

Workaround is to set types manually: `styled.div<React.FunctionComponent<React.HTMLAttributes<HTMLDivElement>>>` 

## Reproducible Demo

Doesn't work
```
import { styled } from '@linaria/react';

const Wrapper = styled.div`
    padding: 10px;
`;

const CancelPage = () => {
    return <Wrapper>x</Wrapper>;
};

export default CancelPage;
```

![image](https://user-images.githubusercontent.com/3653022/142730970-3a75f8c6-a4cf-4a3b-b7a0-9c0a84b5e326.png)

Works:
```
import { styled } from '@linaria/react';
import * as React from 'react';

const Wrapper = styled.div<React.FunctionComponent<React.HTMLAttributes<HTMLDivElement>>>`
    padding: 10px;
`;

const CancelPage = () => {
    return <Wrapper>x</Wrapper>;
};

export default CancelPage;

```

**Comment by Anber** [comment] 2021-11-29 12:28
Hi @fabulator!

I think the problem is in missed `import * as React from 'react';` in the first case. Could you please add it and check?

**Comment by Opty1712** [comment] 2021-12-13 12:54
Have the same issue on TS 4.6 and linaria 1.4.1. Moreover I don't have intellisense support for CSS inside `styled`

**Comment by Opty1712** [comment] 2021-12-13 19:13
@Anber thank you, but it doesn't work. I downgraded TS to 4.3.5 but it doesn't help.
Another idea is `yarn 3`, I use it in my project with `yarn workspaces`

**Comment by Opty1712** [comment] 2021-12-14 08:54
@fabulator do you use yarn / yarn workspaces?
I just checked on my working simple project: updated TS to 4.6 and everything is fine there. Yarn@1, no workspaces

After I upgraded yarn to version 3 - everything is fine.

After moving this simple project to yarn workspaces - it works too. Will try to investigate

**Comment by Opty1712** [comment] 2021-12-24 15:29
@fabulator  Here is the decision. May be I broke anything, but it works for me. Move it's content to `linaria.d.ts` file and include it in `tsconfig`

```ts
/** Override of incorrect Linaria typings */
declare module 'linaria/react' {
	import { FC } from 'react';

	type StyledMeta = {
		__linaria: {
			className: string;
			extends: StyledMeta;
		};
	};

	type CSSProperties = {
		[key: string]: string | number | CSSProperties;
	};

	declare type StaticPlaceholder = string | number | CSSProperties | StyledMeta;

	declare type HtmlStyledTag<TName extends keyof JSX.IntrinsicElements> = <
		TAdditionalProps = REcord<string, unknown>
	>(
		strings: TemplateStringsArray,
		...exprs: Array<
			| StaticPlaceholder
			| ((
					props: JSX.IntrinsicElements[TName] & Omit<TAdditionalProps, never>
			  ) => string | number)
		>
	) => FC<JSX.IntrinsicElements[TName] & TAdditionalProps>;

	declare type StyledJSXIntrinsics = {
		readonly [P in keyof JSX.IntrinsicElements]: HtmlStyledTag<P>;
	};

	declare type Styled = StyledJSXIntrinsics;
	declare const styled: Styled;
}
```

**Comment by Anber** [comment] 2021-12-27 11:50
Could you please provide a sample repo with this error?

**Comment by sotnikov-link** [comment] 2022-01-17 15:04
I have problem too: JSX element type 'Container' does not have any construct or call signatures. ts(2604).
My env: yarn@3 + workspaces, linaria@2.3.1, typescript@4.

```tsx
import { styled } from 'linaria/react';
import React from 'react';

const Title = styled.h1`
  color: red;
`;

const Container = styled.div`
  border: 1px solid red;

  &:hover {
    border-color: blue;
  }

  ${Title} {
    margin-bottom: 24px;
  }
`;

() => (
  <Container color="#333">
    {
      // JSX element type 'Container' does not have any construct or call signatures. ts(2604)
    }
    <Title>Hello world</Title>
    {
      // JSX element type 'Title' does not have any construct or call signatures. ts(2604)
    }
  </Container>
);
```

**Comment by victordidenko** [comment] 2022-02-01 09:29
Adding `esModuleInterop` option to `tsconfig.json` has fixed the issue for me, dunno why ¯\\\_(ツ)\_/¯ 
```diff
{
  "compilerOptions": {
+    "esModuleInterop": true,
```

**Comment by AndrewVorobev** [comment] 2022-03-14 14:09
+1
Have same issue
```
export interface ITextProps extends HTMLElement {
   size: string;
   someOtherCustomProp: unknown;
}

export const TextStyled = styled.div<ITextProps>`
    font-family: 'Noto Sans', sans-serif;
    font-size: ${({size}) => size}
`;

export const Text: FC<ITextProps> = ({ size = '16px', ...props }) => {
    // JSX element type 'TextStyled' does not have any construct or call signatures error
    return <TextStyled  size={size} {...props} />;
};

```

**Comment by princelauvaka** [comment] 2022-10-03 05:57
This worked for me:

**Use**
`import styled from "@emotion/styled"`

**Instead of**
`import styled from "@emotion/react"`

**Comment by fabulator** [comment] 2022-10-30 08:56
With a newer versions I don't have a problem anymore.

**Closed** 2022-10-30 09:06 UTC
Labels: needs: complete repro 🖥️, bug report 🦗
