### ISSUE TITLE
EvalError: (0 , _solidJs.createContext) is not a function

### ISSUE THREAD

**Issue by usmanyunusov** [callstack/linaria#1134] opened 2022-11-24 23:43 UTC
I get the bug when I use `linaria` with `solid-js`.

`EvalError: (0 , _solidJs.createContext) is not a function in`

I think we need to to rule it out as at https://github.com/callstack/linaria/blob/master/packages/utils/src/isUnnecessaryReactCall.ts#L53

**Comment by Anber** [comment] 2022-11-26 17:41
Well… It looks like it's time to decide how we can move those logic from `utils`, to library-specific logic.

**Comment by usmanyunusov** [comment] 2022-11-26 22:14
@Anber, there is a temporary way around it?

**Comment by Anber** [comment] 2022-11-27 09:34
@usmanyunusov I don't think so. Could you please make a repo that reproduces this error?

**Comment by layershifter** [comment] 2023-09-24 20:20
@usmanyunusov this have been fixed in v5, https://stackblitz.com/edit/linaria-bug-uapcv9 🎉

**Closed** 2023-09-25 08:01 UTC
Labels: needs: complete repro 🖥️, bug report 🦗
