### ISSUE TITLE
@linaria/react + @linaria/rollup not working with vite 3.1.0 

### ISSUE THREAD

**Issue by cojoclaudiu** [callstack/linaria#1060] opened 2022-09-07 09:07 UTC
Hi @cojoclaudiu. I don't know. Maybe. We have [an example for Vite](https://github.com/callstack/linaria/blob/master/examples/vite/vite.config.js) (and I use Vite in my projects), and everything works well. Let's see how @iMoses's approach will affect the problem.

_Originally posted by @Anber in https://github.com/callstack/linaria/issues/1057#issuecomment-1238286783_

Hello,
Yesterday I've starting new React + TS project with vite (last version 3.1.0) and I was trying to integrate @linaria/react and @linaria/rollup (both last versions 4.1.2) without any success.

I was checking the vite example from the linaria repo and is working but with vite 2.9. I've posted my errors in this PR https://github.com/callstack/linaria/pull/1057

**Comment by Dmitra** [comment] 2022-09-14 10:04
duplicate of #1044 ?

**Comment by cojoclaudiu** [comment] 2022-09-14 10:14
> duplicate of #1044 ?

I think so

**Closed** 2022-10-17 15:21 UTC
Labels: needs: triage 🏷, bundler: rollup 🗞️
