### ISSUE TITLE
`classNameSlug` function is replacing dashes `-` with underscores `_`

### ISSUE THREAD

**Issue by soluml** [callstack/linaria#563] opened 2020-03-31 16:08 UTC
## Environment
Using `"linaria": "^1.4.0-beta.5"`

## Description
When `classNameSlug` is defined as below, the resulting class name has underscores instead of dashes. I'd expect Linaria to return the exact string with only the variables replaced. If that's not the case, then the allowed characters should be specified in the documentation.

**linaria.config.js:**
```
module.exports = {
  classNameSlug: hash => `wp-${hash}`
};
```

**Output:**
`<section class="wp_e1rrdh3o wp_h1whidvl"> ... </section>`

**Comment by jayu** [comment] 2020-03-31 22:27
This is a duplicate of #554

**Closed by jayu** 2020-03-31 22:27 UTC
Labels: duplicate
