### ISSUE TITLE
Rollup: Using the "styled" tag in runtime is not supported

### ISSUE THREAD

**Issue by Glazy** [callstack/linaria#364] opened 2019-03-22 14:03 UTC
## Environment

`rollup`: `^1.2.2`
`linaria`: `^1.3.1`

## Description

Project is TypeScript + Linaria transpiled via Babel using `@babel/preset-typescript`. The module bundler I am using is `rollup`. Despite having included the `linaria/babel` preset in my `babel.config.js` file I am still seeing an error in the console: `Error: Using the "styled" tag in runtime is not supported. Make sure you have set up the Babel plugin correctly.`

## Reproducible Demo

```javascript
/**
 * babel.config.js
 */

module.exports = {
  presets: [
    '@babel/preset-env',
    '@babel/preset-typescript',
    '@babel/preset-react',
    'linaria/babel',
  ],
};
```

```javascript
/**
 * rollup.config.js
 */

import commonjs from 'rollup-plugin-commonjs';
import resolve from 'rollup-plugin-node-resolve';
import babel from 'rollup-plugin-babel';
import linaria from 'linaria/rollup';
import css from 'rollup-plugin-css-only';
import pkg from './package.json';

const extensions = ['.js', '.jsx', '.ts', '.tsx'];

const name = 'RollupTypeScriptBabel';

export default {
  input: './src/index.ts',

  external: ['react', 'react-dom'],

  plugins: [
    // Allows node_modules resolution
    resolve({ extensions }),

    // Allow bundling cjs modules. Rollup doesn't understand cjs
    commonjs({
      namedExports: {
        '../../node_modules/linaria/react.js': ['styled'],
        '../../node_modules/react-is/index.js': ['isElement', 'isValidElementType', 'ForwardRef'],
      },
    }),

    // Compile TypeScript/JavaScript files
    babel({ extensions, include: ['src/**/*'] }),

    linaria({
      sourceMap: process.env.NODE_ENV !== 'production',
      evaluate: true,
    }),

    css({
      output: 'styles.css',
    }),
  ],

  output: [
    {
      file: pkg.main,
      format: 'cjs',
    },
    {
      file: pkg.module,
      format: 'es',
    },
  ],
};

```

```typescript
/**
 * BasicImageViewer.tsx
 */
import { styled } from 'linaria/react';

const BasicImageViewer = styled.img`
  width: 250px;
  height: 250px;
`;

export default BasicImageViewer;
```

**Comment by satya164** [comment] 2019-03-22 14:21
Can you post your code? How are you importing `styled` tag? If you don't use ES modules to import it, our babel plugin won't understand it. We can add an option to disable this check however if it's important for you.

**Comment by Glazy** [comment] 2019-03-22 14:27
Thanks for the quick response @satya164!

I have updated my original issue with an example component to illustrate my usage :+1:

**Comment by satya164** [comment] 2019-03-22 14:30
I don't have much experience with rollup, so not sure about plugin ordering. Linaria needs to run before babel, have you tried adding the linaria plugin before babel?

**Comment by Glazy** [comment] 2019-03-22 14:33
Yeah, I originally had them the other way round and have just tried it again without success.

```javascript
    // other plugins
    linaria({
      sourceMap: process.env.NODE_ENV !== 'production',
      evaluate: true,
    }),

    // Compile TypeScript/JavaScript files
    babel({ extensions, include: ['src/**/*'] }),
    // more plugins
```

**Comment by satya164** [comment] 2019-03-22 14:36
I'm tagging @johanholmerin who implemented the rollup plugin. Maybe he will be able to help you.

Sorry, I'm not very familiar with rollup.

**Comment by Glazy** [comment] 2019-03-22 14:40
No problem, thanks for your help so far 👊 

Whenever I get this resolved, if I think there is space for improvement, I will make a PR to the rollup section of the documentation :+1:

**Comment by mattoni** [comment] 2019-05-07 01:03
Just wondering if there has been an update to this or if more information is available. I'm running into this as well with a similar setup.

**Comment by jedmao** [comment] 2019-05-28 22:29
I'm getting the same error when using https://github.com/callstack/linaria/issues/285#issuecomment-480587977

**Comment by johanholmerin** [comment] 2019-08-29 13:09
Do you have a repo with a minimal reproduction?

**Comment by mattoni** [comment] 2019-08-30 20:01
Not completely minimal, but here is one that suffers from the issue:

https://github.com/mattoni/linaria-test

**Comment by johanholmerin** [comment] 2019-08-30 21:13
Have already seen that one. Couldn't reproduce. That's why I asked for a minimal repo.

**Comment by mattoni** [comment] 2019-08-31 18:59
@johanholmerin Okay, I tried to create something much more minimal. Let me know if you are able to reproduce

https://github.com/mattoni/linaria-rollup

**Comment by johanholmerin** [comment] 2019-09-01 09:21
If you look at `dist/bundle.js` you can see that Typescript has transpiled the template literal, which means linaria doesn't recognize it. You can fix this by doing one of the following:

- Change `module` to `esnext` in `tsconfig.json`
- Add `@babel/preset-typescript` to `presets` in `.babelrc` and move the typescript plugin to after linaria
- Remove the typescript plugin and use babel instead. Make sure the babel plugin is after the linaria plugin

**Comment by chrstntdd** [comment] 2020-02-22 21:37
Still running into this error as well.  Any updates?

**Comment by tanphamhaiduong** [comment] 2020-05-20 11:17
![image](https://user-images.githubusercontent.com/22660833/82440176-1f722d80-9ac6-11ea-843d-e591833a3811.png)
I'm facing with problem when run jest test. So do anybody know how to solve this?

**Comment by TMaszko** [comment] 2020-05-26 14:15
Solution will be to remove typescript plugin because it is somehow transforming template literals before linaria is able to recognise it.
proper configuration could look like this like this: 
```js
plugins: [babel({
      presets: [
        "linaria/babel",
        "@babel/preset-typescript",
        "@babel/preset-react",
      ],
      extensions: [".ts", ".tsx"],
    }),
...
]
```
or
```js
 plugins: [ babel({
      presets: ["@babel/preset-typescript", "@babel/preset-react"],
      extensions: [".ts", ".tsx"],
    }),
    linaria(),
   ....]
```
Extensions key is important because otherwise `preset-typescript` will not handle typescript files at all.

**Comment by tanphamhaiduong** [comment] 2020-05-27 10:45
@TMaszko I try to use rollup config as you give, but there is an error in runtime css tag not support

**Comment by TMaszko** [comment] 2020-05-27 11:35
@tanphamhaiduong please provide a link to repo where we can reproduce your bug

**Comment by tanphamhaiduong** [comment] 2020-05-27 16:07
@TMaszko I fixed by using this one in package.json
```
babel": {
    "presets": [
      "@babel/preset-env",
      "linaria/babel"
    ]
```
and my roll-up config
```
export default [
  {
    input: 'src/styles/index.scss',
    output: {
      name: 'index',
      format: 'es',
    },
    plugins: [
      babel({
        presets: ['@babel/preset-env', 'linaria/babel'],
        extensions: ['.ts', '.tsx'],
        exclude: 'node_modules/**',
      }),
      linaria({
        sourceMap: process.env.NODE_ENV !== 'production',
        evaluate: true,
      }),
      css({
        output: 'styles.css',
      }),
      scss({
        output: styles => {
          const content = ['./dist/elements.esm.js']
          purify(content, styles, purifyOpions)
        },
      }),
      // Allow bundling cjs modules. Rollup doesn't understand cjs
      commonjs({
        namedExports: {
          '../../node_modules/linaria/react.js': ['styled', 'css'],
          '../../node_modules/react-is/index.js': ['isElement', 'isValidElementType', 'ForwardRef'],
        },
      }),
    ],
  },
]
```
But seems it doesn't bundle to styles.css like config above
```
css({
        output: 'styles.css',
      }),
```
So i'm investigating

**Comment by TMaszko** [comment] 2020-05-28 09:10
Why are you using `evaluate` set to true ?

**Comment by jayu** [comment] 2020-06-16 12:48
I assume that there is a workaround for this issue. Developers has to be very careful with a rollup unfortunately

**Closed by jayu** 2020-06-16 12:48 UTC
Labels: bundler: rollup 🗞️, priority: high ⚠️, status: up for grabs 🙏, workaround exist
