### ISSUE TITLE
Consider simplifying new styles evaluator

### ISSUE THREAD

**Issue by pbitkowski** [callstack/linaria#448] opened 2019-07-04 11:46 UTC
After some investigation the burden of maintaining new extractor is too high. Having to list and manage explicitly all of the syntaxes it's not feasible for us. 

There are still open questions:
1. What additional use cases the new extractor handles than the previous one? 
2. Can we use new extractor logic and get rid of the AST specifics (list of specific language syntaxes / identifiers) ? 

CC: @Anber @thymikee @satya164 @zamotany

**Comment by Anber** [comment] 2019-07-04 11:51
At least it works with any code base, not only with specially prepared. The current one just fails on our project with out of memory exception and returns a lot of `undefined` instead of classes.

**Comment by pbitkowski** [comment] 2019-07-04 11:54
Could you provide repro?

**Comment by Anber** [comment] 2019-07-04 12:04
An example with `undefined` was in original PR:
```
const object = { fontSize: 12 };
object.fontWeight = 'bold';
export default styled.h1`
  ${object};
`;
```

Out of memory happens on our project with 500+ jsx files and I'm afraid, I can not just make a sample repo. It happens because of the current extractor tries to import unnecessary dependencies that also has dependencies…

**Comment by thymikee** [comment] 2019-07-04 12:05
The main concerns we have is about the maintenance, because JS and other compile-to-js languages (e.g. TS, Flow) tend to add new syntaxes once in a while. We unfortunately don't have unlimited bandwidth to contribute to this project. I hope that's understandable. 

Do you think you could help us with that and maintain this part of the codebase? We'd really appreciate that. We admire the work that you did. It also seems to improve some performance issues we had with previous approach (likely fixed with caching, but still). 

I'd like us to think about further simplifying this implementation, e.g. by
- reducing the surface area 
- figuring out if we can subtract some of the code with existing solutions (like code elimination)

**Comment by Anber** [comment] 2019-07-04 12:21
> Do you think you could help us with that and maintain this part of the codebase?

Definitely yes, because we have two big projects that we have already migrated to linaria.

> figuring out if we can subtract some of the code with existing solutions
We can If there is an existing solution. It would be the best option.

Supporting for other languages is not as hard as it sounds. For example, for TS I have just added ≈30 lines of code. The main problem is to find broken samples of code (eg. enums for TS).

**Comment by thymikee** [comment] 2019-07-04 12:35
Awesome! We have plans to move linaria to a monorepo, so the packages scope is better defined: https://github.com/callstack/linaria/issues/413. It should help with owning a specific part of the codebase (we could use CODEOWNERS.md file for that and add you there). That would also be an opportunity to document the approach and code better for current and future contributors, since it's a pretty complex piece of code. I hope you agree :)

**Comment by Anber** [comment] 2019-07-23 10:38
I've just realized, that we do not need to support all features from es, ts, flex, etc. We need to support only the core part (which is pretty simple https://github.com/callstack/linaria/blob/28bdbf1d781b2d966b4b1f12a6e687e8e415169e/src/babel/evaluate/langs/core.ts) because everything else can be transpilled before shaking.
I'll try to make PoC in the near future.

**Comment by layershifter** [comment] 2023-09-30 18:09
The issue is outdated and does not reflect the current state of the project, feel free to open a new issue.

**Closed** 2023-09-30 19:15 UTC
Labels: enhancement: proposal 💬, needs: triage 🏷, cat: performance 🚀
